language: objective-c
before_install:
- gem install cocoapods
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- pod install --project-directory=Example
script:
- xctool -workspace Example/AAKeyboardManager.xcworkspace -scheme AAKeyboardManager-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build
- pod lib lint --quick
